version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
  api:
    container_name: api
    build: ./movies-app/server
    ports:
      - '5000:5000'
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'